# Generated by Django 3.1.1 on 2020-09-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0002_wish_granted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted_by',
        ),
    ]
