# Generated by Django 3.1.1 on 2020-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0003_remove_wish_granted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
