# Generated by Django 3.1.1 on 2020-09-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0005_auto_20200918_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
